#!/usr/bin/env bash

set -o nounset

MYSQL_DB_HOST=${MYSQL_DB_HOST:-mysql}
MYSQL_DB_USER=${MYSQL_DB_USER}
MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
MYSQL_DB_NAME=${MYSQL_DB_NAME}

ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://$ELASTICSEARCH_HOST:9200}

if [ ! -e /var/www/html/config/config.database.php ]; then
	while ! mysql -h "$MYSQL_DB_HOST" -u "$MYSQL_DB_USER" -p"$MYSQL_DB_PASSWORD" --execute "use $MYSQL_DB_NAME" ; do
		echo "Database is not ready yet, waiting..."
		sleep 3
	done

	mysql_command="SELECT COUNT(DISTINCT \`table_name\`) FROM \`information_schema\`.\`columns\` WHERE \`table_schema\` = '$MYSQL_DB_NAME'"
	tables=$(mysql --batch --skip-column-names -h "$MYSQL_DB_HOST" -u "$MYSQL_DB_USER" -p"$MYSQL_DB_PASSWORD" --execute "$mysql_command")

	if [ "$tables" -ne "0" ]; then
		echo -e "Your database is not empty\n\nPlease try again using an empty one"
		exit 1
	fi


	profile=$(mktemp)

	cat <<-EOF > "$profile"
	{
		"no-interactive": true,
		"skip": [
			"checks"
		],
		"install-source": "automated_installer",
		"dbinfo": {
			"host": "MYSQL_DB_HOST",
			"user": "MYSQL_DB_USER",
			"password": "MYSQL_DB_PASSWORD",
			"dbname": "MYSQL_DB_NAME"
		},
		"path_php": "/usr/local/bin/php",
		"path_mysql": "/usr/bin/mysql",
		"path_mysqldump": "/usr/bin/mysqldump",
		"filestorage_method": "fs"
	}
	EOF

	sed -i "s/MYSQL_DB_HOST/${MYSQL_DB_HOST}/" "$profile"
	sed -i "s/MYSQL_DB_USER/${MYSQL_DB_USER}/" "$profile"
	sed -i "s/MYSQL_DB_NAME/${MYSQL_DB_NAME}/" "$profile"

	# password might have slashes, escape them

	MYSQL_DB_PASSWORD=$(sed 's:/:\\/:' <<< "$MYSQL_DB_PASSWORD")

	sed -i "s/MYSQL_DB_PASSWORD/${MYSQL_DB_PASSWORD}/" "$profile"

	cp -r /usr/src/deskpro/* /var/www/html/
	chown -R www-data:www-data /var/www/html/

	cd /var/www/html/ && bin/install --profile "$profile" --no-interaction
fi

exec apache2-foreground
